wandb_version: 1

min_samples:
  desc: null
  value: 10
max_depth:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1708316390.426826
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.10
      5: 0.16.3
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
